/*---------------
--紀錄帳號
---------------*/

CREATE TABLE USERS (
    ACCOUNT VARCHAR2(20 CHAR),
    PASSWORD VARCHAR2(50 CHAR) NOT NULL,
    NAME VARCHAR2(20 CHAR) NOT NULL,
    USER_ID VARCHAR2(36 CHAR) NOT NULL PRIMARY KEY,
    CREDIT NUMBER(20) NOT NULL,
    CREATED_TIME NUMBER(13),
    LAST_LOGIN_TIME NUMBER(13),
    CONSTRAINT UK_USERS1 UNIQUE (ACCOUNT)
);

CREATE INDEX IDX_USER1 ON USERS(ACCOUNT, PASSWORD);

/*---------------
--紀錄會員操作日誌
---------------*/

CREATE TABLE USERS_LOG (
	USER_LOG_ID VARCHAR2(36 CHAR) NOT NULL PRIMARY KEY,
	USER_ID VARCHAR2(36 CHAR) NOT NULL REFERENCES USERS(USER_ID),
	ACTION VARCHAR2(30 CHAR) NOT NULL,
	CREATED_TIME NUMBER(13),
	REMARK VARCHAR2(200 CHAR)
);

CREATE INDEX IDX_USER_LOG1 ON USERS_LOG(USER_ID);

/*---------------
--紀錄商品
---------------*/

CREATE TABLE PRODUCTS (
	ITEM_ID NUMBER(10) PRIMARY KEY,
	ITEM_NM VARCHAR2(30 CHAR) NOT NULL,
	ITEM_PRICE NUMBER(10),
	AMOUNT NUMBER(8),
	CREATED_TIME NUMBER(13)
);

/*---------------
--紀錄購物車
---------------*/
CREATE TABLE CART (
	CART_ID VARCHAR2(36 CHAR) NOT NULL PRIMARY KEY,
	USER_ID VARCHAR2(36 CHAR) REFERENCES USERS(USER_ID),
	ITEM_ID NUMBER(10) NOT NULL REFERENCES PRODUCTS(ITEM_ID),
	AMOUNT NUMBER(8) NOT NULL,
    CONSTRAINT UK_CART1 UNIQUE (USER_ID, ITEM_ID)
);

CREATE INDEX IDX_CART1 ON CART(USER_ID);
CREATE INDEX IDX_CART2 ON CART(ITEM_ID);


/*---------------
--紀錄訂單
---------------*/

CREATE TABLE ORDER_HEADER (
	ORD_NO VARCHAR2(15 CHAR) NOT NULL PRIMARY KEY,
	USER_ID VARCHAR2(36 CHAR) REFERENCES USERS(USER_ID),
	CREATED_TIME NUMBER(13),
	SUB_TOTAL NUMBER(20) NOT NULL
);

CREATE TABLE ORDER_ITEM (
	ORDER_ITEM_ID VARCHAR2(36 CHAR) NOT NULL PRIMARY KEY,
	ORD_NO VARCHAR2(15 CHAR) REFERENCES ORDER_HEADER(ORD_NO),
	ITEM_ID NUMBER(10) NOT NULL REFERENCES PRODUCTS(ITEM_ID),
	AMOUNT NUMBER(8) NOT NULL
);

CREATE INDEX IDX_ORDER_ITEM1 ON ORDER_ITEM(ORD_NO);
