/*---------------
--紀錄帳號
---------------*/

CREATE TABLE USERS (
    ACCOUNT VARCHAR2(20 CHAR),
    PASSWORD VARCHAR2(50 CHAR) NOT NULL,
    NAME VARCHAR2(20 CHAR) NOT NULL,
    USER_ID VARCHAR2(36 CHAR) NOT NULL PRIMARY KEY,
    CREDIT NUMBER(20) NOT NULL,
    CREATED_TIME NUMBER(13),
    LAST_LOGIN_TIME NUMBER(13),
    CONSTRAINT UK_USERS1 UNIQUE (ACCOUNT)
);

CREATE INDEX IDX_USER1 ON USERS(ACCOUNT, PASSWORD);

COMMENT ON TABLE USERS IS '帳號';
COMMENT ON COLUMN USERS.ACCOUNT IS '帳號';
COMMENT ON COLUMN USERS.PASSWORD IS '密碼';
COMMENT ON COLUMN USERS.NAME  IS '姓名';
COMMENT ON COLUMN USERS.USER_ID IS '使用者ID';
COMMENT ON COLUMN USERS.CREDIT IS '信用額度';
COMMENT ON COLUMN USERS.CREATED_TIME IS '建立時間';
COMMENT ON COLUMN USERS.LAST_LOGIN_TIME IS '最後登入時間';

/*---------------
--紀錄會員操作日誌
---------------*/

CREATE TABLE USERS_LOG (
	USER_LOG_ID VARCHAR2(36 CHAR) NOT NULL PRIMARY KEY,
	USER_ID VARCHAR2(36 CHAR) NOT NULL REFERENCES USERS(USER_ID),
	ACTION VARCHAR2(30 CHAR) NOT NULL,
	CREATED_TIME NUMBER(13),
	REMARK VARCHAR2(200 CHAR)
);

CREATE INDEX IDX_USER_LOG1 ON USERS_LOG(USER_ID);

COMMENT ON TABLE USERS_LOG IS '會員操作日誌';
COMMENT ON COLUMN USERS_LOG.USER_LOG_ID IS '使用者LOG ID';
COMMENT ON COLUMN USERS_LOG.USER_ID IS '使用者ID';
COMMENT ON COLUMN USERS_LOG.ACTION IS '使用者操作動作';
COMMENT ON COLUMN USERS_LOG.CREATED_TIME IS '建立時間';
COMMENT ON COLUMN USERS_LOG.REMARK IS '備註';

/*---------------
--紀錄商品
---------------*/

CREATE TABLE PRODUCTS (
	ITEM_ID NUMBER(10) PRIMARY KEY,
	ITEM_NM VARCHAR2(30 CHAR) NOT NULL,
	ITEM_PRICE NUMBER(10),
	AMOUNT NUMBER(8),
	CREATED_TIME NUMBER(13)
);

COMMENT ON TABLE PRODUCTS IS '商品';
COMMENT ON COLUMN PRODUCTS.ITEM_ID IS '商品ID';
COMMENT ON COLUMN PRODUCTS.ITEM_NM IS '商品名稱';
COMMENT ON COLUMN PRODUCTS.ITEM_PRICE IS '商品單價';
COMMENT ON COLUMN PRODUCTS.AMOUNT IS '庫存數量';
COMMENT ON COLUMN PRODUCTS.CREATED_TIME IS '建立時間';

INSERT INTO PRODUCTS (ITEM_ID,ITEM_NM,ITEM_PRICE,AMOUNT,CREATED_TIME) VALUES (1,'狗鍊',38,14850,1549179096162);
INSERT INTO PRODUCTS (ITEM_ID,ITEM_NM,ITEM_PRICE,AMOUNT,CREATED_TIME) VALUES (2,'50吋hd電視',38000,15000,1549179996162);
COMMIT;
/*---------------
--紀錄購物車
---------------*/
CREATE TABLE CART (
	CART_ID VARCHAR2(36 CHAR) NOT NULL PRIMARY KEY,
	USER_ID VARCHAR2(36 CHAR) REFERENCES USERS(USER_ID),
	ITEM_ID NUMBER(10) NOT NULL REFERENCES PRODUCTS(ITEM_ID),
	AMOUNT NUMBER(8) NOT NULL,
    CONSTRAINT UK_CART1 UNIQUE (USER_ID, ITEM_ID)
);

CREATE INDEX IDX_CART1 ON CART(USER_ID);
CREATE INDEX IDX_CART2 ON CART(ITEM_ID);

COMMENT ON TABLE CART IS '購物車';
COMMENT ON COLUMN CART.CART_ID IS '購物車ID';
COMMENT ON COLUMN CART.USER_ID IS '使用者ID';
COMMENT ON COLUMN CART.ITEM_ID IS '商品ID';
COMMENT ON COLUMN CART.AMOUNT IS '購買數量';

/*---------------
--紀錄訂單
---------------*/

CREATE TABLE ORDER_HEADER (
	ORD_NO VARCHAR2(15 CHAR) NOT NULL PRIMARY KEY,
	USER_ID VARCHAR2(36 CHAR) REFERENCES USERS(USER_ID),
	CREATED_TIME NUMBER(13),
	SUB_TOTAL NUMBER(20) NOT NULL
);

COMMENT ON TABLE ORDER_HEADER IS '訂單主檔';
COMMENT ON COLUMN ORDER_HEADER.ORD_NO IS '訂單號碼';
COMMENT ON COLUMN ORDER_HEADER.USER_ID IS '使用者ID';
COMMENT ON COLUMN ORDER_HEADER.CREATED_TIME IS '建立時間';
COMMENT ON COLUMN ORDER_HEADER.SUB_TOTAL IS '訂單總價錢';

CREATE TABLE ORDER_ITEM (
	ORDER_ITEM_ID VARCHAR2(36 CHAR) NOT NULL PRIMARY KEY,
	ORD_NO VARCHAR2(15 CHAR) REFERENCES ORDER_HEADER(ORD_NO),
	ITEM_ID NUMBER(10) NOT NULL REFERENCES PRODUCTS(ITEM_ID),
	AMOUNT NUMBER(8) NOT NULL
);

CREATE INDEX IDX_ORDER_ITEM1 ON ORDER_ITEM(ORD_NO);

COMMENT ON TABLE ORDER_ITEM IS '訂單明細';
COMMENT ON COLUMN ORDER_ITEM.ORDER_ITEM_ID IS '訂單物品ID';
COMMENT ON COLUMN ORDER_ITEM.ORD_NO IS '訂單號碼';
COMMENT ON COLUMN ORDER_ITEM.ITEM_ID IS '商品ID';
COMMENT ON COLUMN ORDER_ITEM.AMOUNT IS '訂單總數量';
